Added greenfield endpoint
Signed-off-by: Renuka Singare <renuka.singare@ibm.com>
Signed-off-by: Mahantesh-R <mahantesh.r@ibm.com>

diff --git a/tests/e2e/iks-cluster b/tests/e2e/iks-cluster
--- a/tests/e2e/iks-cluster
+++ b/tests/e2e/iks-cluster
@@ -865,6 +865,11 @@ fi
 
 IC_REGION="$e2e_ic_region"
 
+if [ -z "$IC_REGION" ]; then
+  echo "ERROR: IC_REGION is not set"
+  exit 1
+fi
+
 # #assign region if env == stage-us-south
 # if [[ "$e2e_env" == "stage-us-south" ]]; then
 #     IC_REGION="us-south"                 # REAL REGION
